before_script:
  - export destdir=/tmp/bfpsinstall
  - mkdir $destdir $destdir/lib/ $destdir/lib/python3.6/ $destdir/lib/python3.6/site-packages/ ; echo "replace return"
  - export PYTHONPATH=$PYTHONPATH:$destdir/lib/python3.6/site-packages/
  - export PATH=$PATH:$destdir/bin/


simple-test:
  script:
    - pwd
    - ls
    - python3 setup.py compile_library --timing-output 1
    - python3 setup.py install --prefix=$destdir
    - python3 $destdir/bin/bfps DNS NSVEparticles --niter_todo 8 --niter_stat 2 --niter_part 2
  tags:
    - fftw3
    - hdf5
    - mpi
    - python3


after_script:
  - rm obj/* ||:
  - rm -r build/* ||:
  - rm -r $destdir ||:

