stages:
- build
- test
- cleanup

build_job:
  stage: build
  script:
    - export destdir=/tmp/bfpsinstall
    - export PYTHONPATH=$PYTHONPATH:$destdir/lib/python3.6/site-packages/
    - export PATH=$PATH:$destdir/bin/


simple-test:
  stage: test
  script:
    - pwd
    - ls
    - which python3
    - source ~/.bashrc
    - which python3
    - python3 setup.py compile_library --timing-output 1
    - python3 setup.py install --prefix=$destdir
    - python3 $destdir/bin/bfps DNS NSVEparticles --niter_todo 8 --niter_stat 2 --niter_part 2
  tags:
    - fftw3
    - hdf5
    - mpi
    - python3


cleanup_job:
  stage: cleanup
  script:
    - if [[ -d $destdir ]] ; then rm -rf $destdir ; fi

